server:
  port: 8077

spring:
  application:
    name: rookie-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      discovery:
        locator:
          enabled: true                     #\u5F00\u542F\u6CE8\u518C\u4E2D\u5FC3\u52A8\u6001\u8DEF\u7531\u529F\u80FD\uFF0C\u5229\u7528\u5FAE\u670D\u52A1\u540D\u79F0\u8FDB\u884C\u8DEF\u7531
      routes:
        - id: after_route                     #\u8DEF\u7531\u7684id,\u6CA1\u6709\u56FA\u5B9A\u89C4\u5219\u4F46\u8981\u6C42\u552F\u4E00\uFF0C\u5EFA\u8BAE\u914D\u5408\u670D\u52A1\u540D
      #    uri: http://localhost:8081         #\u5339\u914D\u540E\u63D0\u4F9B\u670D\u52A1\u7684\u8DEF\u7531\u5730\u5740
          uri: lb://rookie-order
          predicates:
          - Path=/item/get/**                #\u65AD\u8A00\uFF0C\u8DEF\u5F84\u76F8\u5339\u914D\u7684\u8FDB\u884C\u8DEF\u7531

        - id: after_route2                     #\u8DEF\u7531\u7684id,\u6CA1\u6709\u56FA\u5B9A\u89C4\u5219\u4F46\u8981\u6C42\u552F\u4E00\uFF0C\u5EFA\u8BAE\u914D\u5408\u670D\u52A1\u540D
         # uri: http://localhost:8081         #\u5339\u914D\u540E\u63D0\u4F9B\u670D\u52A1\u7684\u8DEF\u7531\u5730\u5740
            uri: lb://rookie-order
          predicates:
          - Path=/item/insert/**

        - id: after_route3                     #\u8DEF\u7531\u7684id,\u6CA1\u6709\u56FA\u5B9A\u89C4\u5219\u4F46\u8981\u6C42\u552F\u4E00\uFF0C\u5EFA\u8BAE\u914D\u5408\u670D\u52A1\u540D
         # uri: http://localhost:8081         #\u5339\u914D\u540E\u63D0\u4F9B\u670D\u52A1\u7684\u8DEF\u7531\u5730\u5740
            uri: lb://rookie-order
          predicates:
            - Path=/item/getPort/**
management:
    endpoints:
      web:
        exposure:
          include: '*'